// gfxfont.h — GFX-compatible proportional font type definitions.
//
// This header is a standalone replacement for the Adafruit GFX Library's
// gfxfont.h.  It is compatible with font files generated by the Adafruit
// font-conversion tools (Fonts/Free*.h etc.) without requiring Arduino or
// the Adafruit GFX library.
//
// Usage: font header files that normally do  #include <Adafruit_GFX.h>
// should instead do  #include "gfxfont.h".

#ifndef GFXFONT_H
#define GFXFONT_H

#include <stdint.h>

// On bare-metal targets PROGMEM is a no-op; const arrays go to flash/ROM
// automatically when the linker places read-only data in flash sections.
#ifndef PROGMEM
#define PROGMEM
#endif

/// Per-glyph metrics and bitmap index for one character.
typedef struct {
    uint16_t bitmapOffset; ///< Offset into the GFXfont bitmap array
    uint8_t  width;        ///< Glyph bitmap width  (pixels)
    uint8_t  height;       ///< Glyph bitmap height (pixels)
    uint8_t  xAdvance;     ///< Horizontal advance (cursor step, pixels)
    int8_t   xOffset;      ///< X offset from cursor to left edge of bitmap
    int8_t   yOffset;      ///< Y offset from baseline to top  of bitmap
                           ///<   (negative = above baseline)
} GFXglyph;

/// Font descriptor — points to the bitmap store and the glyph table.
typedef struct {
    uint8_t  *bitmap;   ///< Packed 1bpp glyph bitmaps (MSB-first, not row-padded)
    GFXglyph *glyph;    ///< Glyph metric array, one entry per character
    uint16_t  first;    ///< Unicode code-point of the first glyph
    uint16_t  last;     ///< Unicode code-point of the last  glyph
    uint8_t   yAdvance; ///< Line height (newline distance, pixels)
} GFXfont;

#endif /* GFXFONT_H */
